name: expandtesting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Step 1 Install Newman
        run: npm install -g newman     
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
      - name: Step 3 Execute collection
        run: newman run ./expandtesting_ci.json -g ./expandtesting_globals.json -r htmlextra --reporter-htmlextra-export ./results/report.html
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: report
            path: ./results/Report.html